[package]
name = "capsule"
version = "0.1.0"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tera = "1.2"
lazy_static = "1.4"
serde = { version = "1.0", features = [ "derive" ] }
include_dir = "0.5"
toml = "0.5"
ckb-tool = { git = "https://github.com/jjyr/ckb-tool.git", tag = "v0.0.1" }
ckb-testtool = { git = "https://github.com/jjyr/ckb-tool.git", tag = "v0.0.1" }
simple-jsonrpc-client = "0.1"
bech32 = "0.6"
secp256k1 = "0.17"
serde_json = "1.0"
chrono = "0.4"
rpassword = "4.0"
serde_yaml = "0.8.11"
users = "0.10"
clap = "2.33"
ctrlc = "3.1"
env_logger = "0.7"
log = "0.4"

[workspace]
members = [
    "tests",
]
