# path of deployment config file
deployment = "deployment.toml"
# path of contracts workspace dir, default is the project dir
# workspace_dir = "."

[[contracts]]
name = "{{name}}"
template_type = "Rust"
