# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "{{ version }}"
# path of deployment config file
deployment = "deployment.toml"
