name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install rust format
      run: rustup component add rustfmt
    - name: check format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build
    - name: Install dependencies
      run: cargo install --version 0.7.2 moleculec
    - name: Run tests
      run: cargo run -p tests
