name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Install dependencies
      run: cargo install --version 0.6.0 moleculec
    - name: Run tests
      run: cargo run -p tests
